locale                   : "en-US"
title: Hannahs Personal Site
description: Hannahs Personal Site
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://scholzhannah.de" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  hannahscholz
repository: scholzhannah/scholzhannah.github.io

# Build settings
markdown: kramdown
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Site Author
author:
  name             : "Hannah Scholz"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Maths Master's student at University of Bonn"
  location         : "Bonn, Germany"
  email            :
  links:
    - label: "University Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:scholz.hannah@uni-bonn.de"
    - label: "Personal Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:scholz.hannah@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://scholzhannah.de"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/scholzhannah/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "University Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:scholz.hannah@uni-bonn.de"
    - label: "Personal Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:scholz.hannah@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://scholzhannah.de"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/scholzhannah/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOLuHKvg"
    category_name        : "Announcements"
    category_id          : "DIC_kwDOLuHKvs4Cu43P"
    discussion_term      : "title"
    reactions_enabled    : '1'
    theme                : "light"